name: CI

on:
  workflow_dispatch:
  pull_request:
    paths:
    - '.github/workflows/ci.yml'
    - 'src/**'
    - 'test/**'
    - 'Kiyote.Geometry.sln'
    - 'Directory.Packages.props'
    - 'Directory.Build.props'
    - 'nuget.config'
  push:
    branches: [main]

env:
  DOTNET_VERSION: 8.0.401
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true

permissions:
  pull-requests: write
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            ${{ env.DOTNET_VERSION }}
            
      - name: Define global.json
        run: dotnet new globaljson --sdk-version ${{ env.DOTNET_VERSION }}
          
      - name: Create tool manifest
        run: dotnet new tool-manifest
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}        

      - name: Install dotnet-coverage
        run: dotnet tool install dotnet-coverage
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      
      - name: Build and Test
        run: dotnet test /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=cobertura

      - name: Generate coverage file
        run: dotnet dotnet-coverage merge -o coverage.xml **/coverage.cobertura.xml -f cobertura
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

      - name: Create Orphan Branch
        shell: bash
        run: ${{ github.workspace }}/create-orphan-branch.sh badges ${{ github.ref_name }}

      - name: Make Coverage Badge      
        uses: action-badges/cobertura-coverage-xml-badges@0.3.1
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          file-name: coverage.svg
          badge-branch: badges
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          coverage-file-name: ./coverage.xml    
